django_proj/django_proj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django_proj import views
urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^my_app/',include('my_app.urls')),
    url(r'^$', views.index, name='index'),
    
    ]

django_proj/my_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from my_app import views
app_name = 'my_app'
urlpatterns = [
url(r'^about/$', views.about, name='about'),
url(r'^register/$', views.register, name='register'),
url(r'^login_user/$', views.login_user, name='login_user'),
url(r'^logout_user/$',views.logout_user, name='logout_user')
    ]

django_proj/my_app/models.py
from django.db import models
# Create your models here.

django_proj/my_app/forms.py
from django.forms import ModelForm
from django.contrib.auth.models import User
from django import forms


class User_details_form(ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta:
        model=User
        fields=('username','email','password')

user_form=User_details_form()

django_proj/django_proj/views.py
from django.shortcuts import render

def index(request):
    return render(request,'index.html',{})

django_proj/my_app/views.py
from django.shortcuts import render
from my_app.forms import User_details_form
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
# Create your views here.
def about(request):
    return render(request,'my_app/about.html')

def register(request):
    user_form=User_details_form(data=request.POST)
    registered=False
    if request.method == 'POST':

        if user_form.is_valid():
            registered=True
            print("working")
            dict={}
            user=user_form.save()
            user.set_password(user.password)
            user.save()
            return render(request,'my_app/thanks.html',context=dict)

    dict={'User_Form':user_form,'is_registered':registered}
    return render(request,'my_app/register.html',context=dict)

def login_user(request):

    if request.method=='POST':

            dict={}
            u_name=request.POST.get('user_name')
            u_password=request.POST.get('user_password')
            user=authenticate(username=u_name,password=u_password)
            if user:

                if user.is_active:
                    # Log the user in.
                    login(request,user)

                    # Send the user back to some page.
                    # In this case their homepage.
                    return HttpResponseRedirect(reverse('index'))


            else:
                return render(request,'my_app/login_user.html',context={"message":"Invalid username or password"})

    return render(request,'my_app/login_user.html',context={"message":"Please enter the login details"})

@login_required
def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

django_proj/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>{% block heading %}

    {% endblock %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
  </head>
  <body>
    <ul class="nav navbar-expand-lg navbar-light bg-light">
      <li class="nav-item">
        <a class="nav-link" href="{%url "index"%}">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{%url "my_app:about"%}">About Chatbot</a>
      </li>
      {%if user.is_authenticated%}
      {%else%}
        <li class="nav-item">
          <a class="nav-link" href="{%url "my_app:register"%}">Register</a>
        </li>
      {%endif%}
      {% if user.is_authenticated %}
        <li class="nav-item">
          <a  class="nav-link" href="{%url "my_app:logout_user"%}">Logout</a>
        </li>
      {% else %}
      <li class="nav-item">
        <a class="nav-link" href="{%url "my_app:login_user"%}">Login</a>
      </li>
      {% endif %}

      <li class="nav-item">
        <a class="nav-link " href="{%url "admin:index"%}">Admin</a>
      </li>
    </ul>
    {% block myblock %}

    {% endblock %}
  </body>
</html>

django_proj/templates/index.html
    {% extends "base.html" %}
    {% block heading %}
      home
    {% endblock %}
    {% block myblock %}
    <div class="container">
      <div class="jumbotron">
        ChatBot Coming soon... Stay Tuned!!!!
      </div>
    </div>
    {% endblock %}

django_proj/templates/my_app/about.html
{% extends "base.html" %}
{% block myblock %}
<div class="container">
  <h4>Chat bot is an initiative by EEx Bangalore to replace the L1 Support with the help of Artificail Intelligence</h4>

</div>

{% endblock %}

django_proj/templates/my_app/failure.html
{% extends "base.html" %}
{% block myblock %}
  Login attempt unsuccessfull!!
{% endblock %}

django_proj/templates/my_app/login_user.html
{% extends "base.html" %}
{% block myblock %}

    <div class="container">
      <h3>{{message}}</h3>
      <form method="post" action="{%url 'my_app:login_user'%}" >
        Name<input type="text" name="user_name" >
        password <input type="password" name="user_password" >
        {% csrf_token %}
        <button type="submit" class="btn btn-primary">Submit</button>
      </form>


    </div>


{% endblock %}

django_proj/templates/my_app/register.html
{% extends "base.html" %}

{% block myblock %}
<div class="container">
  <div class="form-group">

    <form method="post" >

      <table>
        <tr>
          <td>Name </td>
          <td>{{User_Form.username}}</td>
        </tr>
        <tr>
          <td>Email</td>
          <td>{{User_Form.email}}</td>
        </tr>
        <tr>
          <td>Password</td>
          <td> {{User_Form.password}}</td>
        </tr>
        
      </table>
      {% csrf_token %}
      <input type="submit" name="submit" value="click here!">

   </form>
  </div>
</div>


{% endblock %}

django_proj/templates/my_app/success.html
{% extends "base.html" %}
{% block myblock %}

Successfully Logged in !!
{% endblock %}

django_proj/templates/my_app/thanks.html
{% extends "base.html" %}
{% block myblock %}
  Thanks for registering!!
{% endblock %}